#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C

cargo test -p local-core export_bindings --quiet
cargo test -p workspace-format export_bindings --quiet
generated=packages/shared/src/generated
mkdir -p "$generated"
find "$generated" -name '*.ts' -delete
cp crates/local-core/bindings/*.ts "$generated/"
cp crates/workspace-format/bindings/*.ts "$generated/"

# One barrel for every generated type, so @noura/shared can re-export them
# without a hand-maintained list that drifts from the Rust sources.
{
	echo '// This file was generated by scripts/sync-bindings.sh. Do not edit this file manually.'
	for file in "$generated"/*.ts; do
		name=$(basename "$file" .ts)
		[ "$name" = index ] && continue
		echo "export type { $name } from './$name';"
	done
} > "$generated/index.ts"
