// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentDescriptor } from "./DocumentDescriptor";
import type { ObjectGrant } from "./ObjectGrant";
import type { PolicyEnvelope } from "./PolicyEnvelope";

export type AccessObject = { document?: DocumentDescriptor, objectId: string, epoch: number, grants: Array<ObjectGrant>, envelopes: Array<PolicyEnvelope>, };
