// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiContentPart = { "type": "text", text: string, } | { "type": "toolCall", callId: string, name: string, arguments: unknown, } | { "type": "toolResult", callId: string, name?: string, content: string, };
