// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiConsentDataCategory } from "./AiConsentDataCategory";

export type AiConsentGrantInput = { providerId: string, policyVersion: string, dataCategory: AiConsentDataCategory, };
