// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiModelRef } from "./AiModelRef";
import type { AiToolDefinition } from "./AiToolDefinition";
import type { AiTransportMessage } from "./AiTransportMessage";

export type AiStreamInput = { operationId: string, model: AiModelRef, messages: Array<AiTransportMessage>, tools?: Array<AiToolDefinition>, policyVersion?: string, };
