// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiModelRef } from "./AiModelRef";
import type { AiStreamSummary } from "./AiStreamSummary";
import type { AiToolCall } from "./AiToolCall";
import type { CoreError } from "./CoreError";

export type AiStreamEvent = { "type": "started", model: AiModelRef, } | { "type": "textDelta", text: string, } | { "type": "toolCall", call: AiToolCall, } | { "type": "completed", summary: AiStreamSummary, } | { "type": "cancelled" } | { "type": "error", error: CoreError, };
