// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiStreamEvent } from "./AiStreamEvent";

export type AiStreamFrame = { operationId: string, 
/**
 * Serialized as a JSON number; a stream never approaches 2^53 frames.
 */
sequence: number, event: AiStreamEvent, };
