// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiModelRef } from "./AiModelRef";
import type { AiStopReason } from "./AiStopReason";
import type { AiUsage } from "./AiUsage";

export type AiStreamSummary = { model: AiModelRef, usage: AiUsage | null, stopReason: AiStopReason | null, };
