// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarEntry = { sourceId: string, sourceType: string, title: string, 
/**
 * The date property this entry comes from; the calendar query only
 * reads `due`, `date`, and `start`.
 */
property: "due" | "date" | "start", start: string, end: string | null, allDay: boolean, revision: string, };
