// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarEntry = { sourceId: string, sourceType: string, title: string, property: string, start: string, end: string | null, allDay: boolean, revision: string, };
