// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chat } from "./Chat";
import type { ChatMessage } from "./ChatMessage";

export type ChatRead = { chat: Chat, messages: Array<ChatMessage>, };
