// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessageKind } from "./ChatMessageKind";
import type { ChatMessageStatus } from "./ChatMessageStatus";

export type ChatMessage = { id: string, chatId: string, runId: string, kind: ChatMessageKind, status: ChatMessageStatus, contentType: string, content: string, relativePath: string, revision: string, created: string, updated: string, providerId: string | null, modelId: string | null, toolCallId: string | null, toolName: string | null, errorCode: string | null, summarizesThroughMessageId: string | null, properties: Record<string, unknown>, };
