// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CollaborationConflictReview = { reviewId: string, objectId: string, generation: string, reason: string, retainedDraft: boolean, competingBytes: boolean, };
