// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollaborationBootstrapRole } from "./CollaborationBootstrapRole";
import type { CollaborationStatus } from "./CollaborationStatus";

export type CollaborationSession = { objectId: string, generation: string, sessionId: string, update: string, revision: string, readOnly: boolean, role: CollaborationBootstrapRole, status: CollaborationStatus, };
