// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollaborationStatus } from "./CollaborationStatus";

export type CollaborationStatusEvent = { objectId: string, generation: string, status: CollaborationStatus, };
