// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationKind } from "./OperationKind";

/**
 * Transport envelope compatible with the server's version-one protocol.
 */
export type EncryptedOperation = { generation?: string, kind?: OperationKind, version: 1 | 2, operationId: string, workspaceId: string, objectId: string, deviceId: string, epoch: number, policyRevision: string, nonce: string, ciphertext: string, signature: string, };
