// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What caused a core event.
 */
export type EventSource = "application" | "external" | "reconciliation" | "sync";
