// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessageStatus } from "./ChatMessageStatus";

export type FinishChatAssistantInput = { chatId: string, messageId: string, content: string, status: ChatMessageStatus, errorCode: string | null, expectedChatRevision: string, expectedMessageRevision: string, };
