// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedConflictResolution } from "./ManagedConflictResolution";

export type ManagedConflictResolveInput = { id: string, currentRevision: string, localTitle: string, localBody: string, localProperties: Record<string, unknown>, resolution: ManagedConflictResolution, };
