// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceObject } from "./WorkspaceObject";

export type ManagedDraftResult = { "status": "unchanged", current: WorkspaceObject, } | { "status": "merged", current: WorkspaceObject, title: string, body: string, properties: Record<string, unknown>, } | { "status": "conflict", current: WorkspaceObject, };
