// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Draft state captured by a client before a managed object was modified.
 * Title, body, and properties are reconciled independently during merges;
 * stable identity and canonical metadata always come from the file.
 */
export type ManagedDraftInput = { id: string, baseRevision: string, baseTitle: string, baseBody: string, baseProperties: Record<string, unknown>, localTitle: string, localBody: string, localProperties: Record<string, unknown>, };
