// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RawMarkdownRead } from "./RawMarkdownRead";
import type { WorkspaceObject } from "./WorkspaceObject";

export type MarkdownLinkTarget = { "kind": "managed", object: WorkspaceObject, } | { "kind": "markdown", document: RawMarkdownRead, } | { "kind": "asset", relativePath: string, } | { "kind": "unresolved" };
