// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ObjectPatch = { title: string | null, body: string | null, properties: Record<string, unknown>, removeProperties: Array<string>, expectedRevision: string, };
