// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RawMarkdownRead } from "./RawMarkdownRead";
import type { WorkspaceObject } from "./WorkspaceObject";

export type RawConflictResolveResult = { current: RawMarkdownRead, managedObject: WorkspaceObject | null, };
