// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Complete current contents of one Markdown file addressed by relative path.
 * Raw files expose their full bytes as UTF-8 text with CRLF normalized to LF;
 * uses-crlf and has-bom flags are preserved for faithful writes.
 */
export type RawMarkdownRead = { relativePath: string, body: string, revision: string, usesCrlf: boolean, hasBom: boolean, };
