// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RawSaveInput = { relativePath: string, baseRevision: string, baseBody: string, localBody: string, };
