// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictResolution } from "./ConflictResolution";

export type ResolveConflictInput = { id: string, currentRevision: string, localBody: string, resolution: ConflictResolution, };
