// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncResolutionChoice } from "./SyncResolutionChoice";

export type ResolveSyncConflict = { operationId: string, currentRevision: string | null, choice: SyncResolutionChoice, };
