// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchResult = { objectId: string | null, objectType: string | null, relativePath: string, title: string, snippet: string, score: number, revision: string, };
