// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncInvitationRole } from "./SyncInvitationRole";

export type SyncInvitationLink = { id: string, role: SyncInvitationRole, inviteUrl: string, expiresAt: string, };
