// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncDevice } from "./SyncDevice";
import type { SyncInvitationRole } from "./SyncInvitationRole";
import type { SyncInvitationStatus } from "./SyncInvitationStatus";

export type SyncInvitation = { id: string, role: SyncInvitationRole, accountId: string | null, status: SyncInvitationStatus, expiresAt: string, devices: Array<SyncDevice>, };
