// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A managed Markdown object and its derived local metadata.
 */
export type WorkspaceObject = { id: string, type: string, title: string, body: string, relativePath: string, revision: string, created: string | null, updated: string | null, properties: Record<string, unknown>, };
