// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceSyncActivationStatus = { activationId: string, objectId: string, path: string | null, installed: boolean, };
