// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Owner-signed authorization to create collaborative generations in a workspace.
 */
export type WorkspaceCapability = { version: 1, workspaceId: string, collaborationVersion: 1, minimumClientVersion: 1, minimumRelayVersion: 1, deviceId: string, signature: string, };
