// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspacePhase = "idle" | "opening" | "scanning" | "indexing" | "ready" | "rebuilding" | "failed";
